# # this file uses prebuilt image in dockerhub
# services:
#   jekyll:
#     image: amirpourmand/al-folio:latest
#     build: .
#     ports:
#       - 8080:8080
#       - 35729:35729
#     volumes:
#       - .:/srv/jekyll
#     environment:
#       - JEKYLL_ENV=development


# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:latest
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - bundle-data:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle-data:
